spring:
  application:
    name: fullstackmall-backend
  
  # 使用H2内存数据库进行测试
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  
  # H2数据库配置
  h2:
    console:
      enabled: true
  
  # JPA配置
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
  
  # 开发环境配置
  devtools:
    restart:
      enabled: true

# 服务器配置
server:
  port: 8080
  servlet:
    context-path: /api

# JWT配置
jwt:
  secret: fullstackmall-secret-key-for-jwt-token-generation-and-validation
  expiration: 86400000 # 24小时，单位毫秒

# 日志配置
logging:
  level:
    com.fullstackmall: DEBUG
    org.springframework.security: DEBUG
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss} - %msg%n'

# Knife4j API文档配置
knife4j:
  enable: true
  setting:
    language: zh_cn
    enable-version: true
    enable-reload-cache-parameter: false
    enable-after-script: true
    enable-filter-multipart-apis: false
    enable-filter-multipart-api-method-type: POST
    enable-request-cache: true
    enable-host: false
    enable-host-text: 
    enable-home-custom: true
    home-custom-path: classpath:markdown/home.md
    enable-search: true
    enable-footer: false
    enable-footer-custom: true
    footer-custom-content: Apache License 2.0 | Copyright  2024 FullStackMall
    enable-dynamic-parameter: false
    enable-debug: true
    enable-open-api: false
    enable-group: true
  cors: true
  production: false
  basic:
    enable: false

# SpringDoc配置（Knife4j基于此）
springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
  swagger-ui:
    enabled: false
  show-actuator: true
  writer-with-default-pretty-printer: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json

# Actuator配置（健康检查）
management:
  endpoints:
    web:
      exposure:
        include: health,info,mappings
  endpoint:
    health:
      show-details: when-authorized